# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2017, 12, 20, 8, 54, 17, 890973, tzinfo=utc))),
                ('importance', models.IntegerField(default=0)),
            ],
        ),
    ]
