# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 21, 11, 39, 57, 385260, tzinfo=utc)),
        ),
    ]
