# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_rest', '0003_auto_20171214_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 6, 37, 48, 584292, tzinfo=utc)),
        ),
    ]
