# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_rest', '0004_auto_20171215_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
